version: "3.2"
services:
  web:
    build: './web/'
    container_name: app
    depends_on:
      - php
      - mysql
    ports:
      - '8080:80'
    networks:
      - frontend
      - backend
    volumes:
      - ./app:/var/www/html/
  php:
    build: './php/'
    container_name: php
    networks:
      - backend
    volumes:
      - ./app:/var/www/html/
  mysql:
    build: './mysql'
    container_name: mysql
    networks:
      - backend
    ports:
      - '3306:3306'
    volumes:
      - ./my-data/db:/var/lib/mysql
  bs:
    image: ustwo/browser-sync
    container_name: bs
    command: start --proxy "web:80" --files "**/*"
    volumes:
      - ./app/:/source
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - web
    networks:
      - backend
      - frontend
networks:
  frontend:
  backend: